Validate comma separated variables
GoogleCloudPlatform/firebase-extensions pull request #25
Opened 2023-05-09 17:33 UTC by Rafer45

2023-05-11 09:34 UTC, pr-Mais requested changes

2023-05-11 09:34 UTC, pr-Mais commented on firestore-palm-gen-text/extension.yaml
> +    validationRegex: ^[A-Za-z]+(,[A-Za-z]+)*$
```suggestion
    validationRegex: ^[a-zA-Z_][a-zA-Z0-9_]{0,99}(,[a-zA-Z_][a-zA-Z0-9_]{0,99})*$
```

2023-05-11 09:34 UTC, pr-Mais commented on firestore-palm-gen-text/extension.yaml
> +      Trailing commas and empty variable names are not allowed.
```suggestion
    validationErrorMessage: >-
      Field names may only use upper and lowercase letters from A to Z or,
      underscores, followed by any sequence of letters, nymbers, or underscores.
      Field names shouldn't exceed 100 characters and may only be separated by
      commas. Trailing commas and empty variable names are not allowed.
```

2023-05-11 09:38 UTC, pr-Mais commented on firestore-palm-gen-text/extension.yaml
> +    validationRegex: ^[A-Za-z]+(,[A-Za-z]+)*$
Fixes #39, Firestore allows numbers, underscores and capital letters in field names

2023-05-17 16:18 UTC, huangjeff5 approved these changes

2023-05-17 17:03 UTC, pr-Mais approved these changes

2023-05-17 17:13 UTC, merged