feat: vertex and image compression
GoogleCloudPlatform/firebase-extensions pull request #340
Opened 2024-01-16 12:48 UTC by cabljac

2024-01-16 13:04 UTC, pr-Mais commented on firestore-genai-chatbot/README.md
> +* Gemini API Provider: This extension makes use of the Gemini family of large language models. For Google AI you will require an API key, whereas Vertex AI will authenticate using application default
Could add a resource for those not familiar with ADC, i.e. https://firebase.google.com/docs/admin/setup#initialize-sdk

2024-01-19 11:25 UTC, pr-Mais requested changes

2024-01-19 11:25 UTC, pr-Mais commented on firestore-genai-chatbot/extension.yaml
> +      see the [docs]https://firebase.google.com/docs/admin/setup#initialize-sdk.
```suggestion
      see the [docs](https://firebase.google.com/docs/admin/setup#initialize-sdk).
```

2024-01-19 11:25 UTC, pr-Mais commented on firestore-multimodal-genai/PREINSTALL.md
> +### Troubleshooting timeout/PROCESSING errors
shouldn't this be in POSTINSTALL?

2024-01-19 11:25 UTC, pr-Mais commented on firestore-multimodal-genai/extension.yaml
> +      see the [docs]https://firebase.google.com/docs/admin/setup#initialize-sdk.
```suggestion
      see the [docs](https://firebase.google.com/docs/admin/setup#initialize-sdk).
```

2024-01-19 13:17 UTC, cabljac commented on firestore-multimodal-genai/PREINSTALL.md
> +### Troubleshooting timeout/PROCESSING errors
hm yeah i agree

2024-01-24 10:01 UTC, merged